### ISSUE TITLE
Update actions to use to 'node20'

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/actions#1]
see 
https://github.com/r-lib/actions/issues/792

**Comment by CeresBarros** [comment]
all good with `r-lib/actions/setup-r-dependencies@v2`
https://github.com/r-lib/actions/issues/792#issuecomment-1918637083

**Comment by achubaty** [comment]
But note that many of our package check workflows still need to be updated because they use eg cache action v3 instead of v4.

I've started working through them and pushing updates already - but some workflows are failing and might take a bit more time to fix.

**Comment by CeresBarros** [comment]
Indeed, but that's not directly related to this repo (at least I couldn't find uses of other actions other than the noted one) - hence why I closed. 
We should open issues for each package -- I can do that.

**Comment by achubaty** [comment]
You're right, but I don't think we need to open so many issues -- we have too many repos 😵‍💫

I've done a local find and replace on everything on my local machine which will capture most of them.

I'll post the list of completed repos in Zulip and we can create issues for any repos not on that list.

**Comment by psolymos** [comment]
I noticed these Node warnings all over, I am glad that you are on to of these.
